# Generated by Django 4.0.3 on 2022-03-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pidtype',
            name='name',
            field=models.CharField(blank=True, help_text='EGN, FPI or UIN', max_length=3, null=True, unique=True, verbose_name='Personal Identifier Type'),
        ),
    ]
