# Generated by Django 4.0.3 on 2022-03-30 09:12

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_alter_profile_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(30)])),
                ('male_min', models.FloatField(validators=[utils.validators.validate_value_not_negative])),
                ('male_max', models.FloatField(validators=[utils.validators.validate_value_not_negative])),
                ('female_min', models.FloatField(validators=[utils.validators.validate_value_not_negative])),
                ('female_max', models.FloatField(validators=[utils.validators.validate_value_not_negative])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
