# Generated by Django 4.0.3 on 2022-03-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0005_analysisfield'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Analysis',
        ),
    ]
