# Generated by Django 4.0.3 on 2022-03-30 09:23

import django.core.validators
from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0006_delete_analysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(30)])),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tat', models.IntegerField(validators=[utils.validators.validate_value_not_negative])),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('analysis_field', models.ManyToManyField(to='laboratory.analysisfield')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
