# Generated by Django 4.0.3 on 2022-03-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0008_alter_analysis_analysis_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='analysis_field',
            field=models.ManyToManyField(blank=True, to='laboratory.analysisfield'),
        ),
    ]
