# Generated by Django 4.0.3 on 2022-03-30 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0014_rename_units_analysisfield_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisfield',
            name='name',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
