# Generated by Django 4.0.3 on 2022-04-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0024_rename_result_resultline_result_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultline',
            old_name='analysis_field_id',
            new_name='analysis_field',
        ),
    ]
