# Generated by Django 4.0.3 on 2022-04-01 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0025_rename_analysis_field_id_resultline_analysis_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultline',
            old_name='analysis_field',
            new_name='analysis_field_id',
        ),
    ]
