# Generated by Django 4.0.3 on 2022-04-01 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0026_rename_analysis_field_resultline_analysis_field_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultline',
            old_name='analysis_field_id',
            new_name='analysis_field',
        ),
        migrations.RenameField(
            model_name='resultline',
            old_name='result_id',
            new_name='result',
        ),
    ]
