# Generated by Django 4.0.3 on 2022-04-05 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0028_sample_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysis',
            options={'verbose_name_plural': 'Analyses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='healthfacility',
            options={'verbose_name_plural': 'HealthFacilities'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name_plural': 'Sexes'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name_plural': 'Specialties'},
        ),
    ]
