# Generated by Django 4.0.3 on 2022-04-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0030_alter_analysis_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacility',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratory.city'),
        ),
    ]
