# Generated by Django 4.0.3 on 2022-03-28 15:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_limsuser_is_deleted_limsuser_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limsuser',
            name='username',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
